version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
      tags:
        - ${DOCKER_USERNAME}/reverseproxy:latest
    image: ${DOCKER_USERNAME}/reverseproxy:${TAG}
  backend_user:
    build:
      context: ./udagram-api-user
      tags:
        - ${DOCKER_USERNAME}/udagram-api-user:latest
    image: ${DOCKER_USERNAME}/udagram-api-user:${TAG}
  backend_feed:
    build:
      context: ./udagram-api-feed
      tags:
        - ${DOCKER_USERNAME}/udagram-api-feed:latest
    image: ${DOCKER_USERNAME}/udagram-api-feed:${TAG}
  frontend:
    build:
      context: ./udagram-frontend
      tags:
        - ${DOCKER_USERNAME}/udagram-frontend:latest
    image: ${DOCKER_USERNAME}/udagram-frontend:${TAG}