apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: luifersuarez/udagram-api-feed
        resources:
          limits:
            memory: 2Gi
            cpu: 1
          requests:
            memory: 1Gi
            cpu: 0.5
        envFrom:
        - secretRef:
            name: aws-secret
        - secretRef:
            name: udagram-secrets
        - configMapRef:
            name: udagram-configmap
      restartPolicy: Always