apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: luifersuarez/udagram-frontend
        resources:
          limits:
            memory: 1Gi
            cpu: 0.5
          requests:
            memory: 0.5Gi
            cpu: 0.25
        ports:
        - containerPort: 80
      restartPolicy: Always
